---
title: "Homework 3"
author: 'BBIC: Bovee, Bichay, Iseneker, Coeman'
date: "2/8/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1
### OLS function

First we simulate data for our LM 

```{r}
### simulate data

library(MASS)
set.seed(6886)
data = mvrnorm(
    n=100, mu=c(-2, 3), 
    Sigma=matrix(c(8,3,3,2),nrow=2,ncol=2) 
)
colnames(data) = c('y','x')
```

Here we create the function that calculates an OLS model manually. Comments within explain each step.  

```{r}
### create function

my_lm <- function(q, p){


# load data

x = as.matrix(cbind(1,p))
y = as.matrix(q)

# calculate b

beta = solve( t(x) %*% x) %*%t (x) %*% y

# calculate vcv and se

yhat <- x %*% beta   # predicted values

ssr <- sum((yhat - y)^2)   # sum of squared residuals

# set N = number of observations; k = number of variables (incl. intercept)

N <- nrow(y)
k <- ncol(x)

sigma2 <- (ssr/(N-k))   # variance

vcv <- (sigma2)*(solve( t(x) %*% x ))   # vcv

se <- sqrt(diag(vcv))

# output results

model_summary <- matrix(c(beta, se), nrow=2, ncol=2, 
                        dimnames=list( c("b0", "b1"),
                            c("Coef", "S.E."))
                        )

return(model_summary)

}

my_lm(data[,"y"], data[,"x"])

```





# Problem 2
### "Create this" matrix





# Problem 3
### Polity matrix and summary stats








# Problem 4
### Merging the other variables






# Problem 5
### Hadley problems





